const Menu = [

  {
    id: 1,
    image: "images/allupakoida.jpg",
    name: "allu pakoida",
    category: "breakfast",
    price: "20₹",
    text: "---------------------------------------------------------------------",
  },
  {
    id: 2,
    image: "images/maggi.jpg",
    name: "maggi",
    category: "breakfast",
    price: "12₹",
    text: "---------------------------------------------------------------------",
  },
  {
    id: 3,
    image: "images/corn.jpg",
    name: "corn",
    category: "evening",
    price: "10₹",
    text: "---------------------------------------------------------------------",
  },
  {
    id: 4,
    image: "../images/pav.jpg",
    name: "Pav Bhaji",
    category: "dinner",
    price: "250₹",
    text: "---------------------------------------------------------------------",
  }, 
  {
    id: 5,
    image: "../images/nonvegthali.jpg",
    name: "Non-Veg Thali",
    category: "dinner",
    price: "180₹",
    text: "---------------------------------------------------------------------",
  },
  {
    id: 6,
    image: "../images/chola.jpg",
    name: "chola",
    category: "lunch",
    price: "60₹",
    text: "---------------------------------------------------------------------",
  },
  {
    id: 7,
    image: "../images/pizza.jpg",
    name: "pizza",
    category: "evening",
    price: "80₹",
    text: "---------------------------------------------------------------------"
  },
  {
    id: 8,
    image: "../images/poha.jpg",
    name: "Poha",
    category: "breakfast",
    price: "25₹",
    text: "---------------------------------------------------------------------",
  }, 
  {
    id: 9,
    image: "../images/sweet.jpg",
    name: "Sweets",
    category: "evening",
    price: "60₹",
    text: "---------------------------------------------------------------------",
  },
  {
    id: 10,
    image: "../images/rajmarice.jpg",
    name: "Rajma Rice",
    category: "lunch",
    price: "60₹",
    text: "---------------------------------------------------------------------",
  },
  {
    id: 11,
    image: "../images/samosa.jpg",
    name: "samaso",
    category: "evening",
    price: "15₹",
    text: "---------------------------------------------------------------------",
  },
  {
    id: 12,
    image: "../images/gujarati.jpg",
    name: "Gujarati Thali",
    category: "dinner",
    price: "150₹",
    text: "---------------------------------------------------------------------",
  }, 
];

export default Menu;
